/*Spring:
 datasource:
   password: Owe22Phila20
   url: jdbc:mysql://localhost:3306/storesdb
   username: root
   spring:
     main:
 Jpa:
   hibernate:
     ddl-auto: update
   Properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
     show-sql: true

